apiVersion: v1
kind: Service
metadata:
  name: cloud-computing
spec:
  selector:
    app: cloud-computing
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http