# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  test:
  
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
    
      - name: unittests
        run: mvn test
      
  SonarCloud-Analysis:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Analyze with SonarCloud         
    
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the sonarcloud scanner
          args:             
            -Dsonar.projectKey=hartwilo_CloudComputing
            -Dsonar.organization=hartwilo

  Notification:
  - name: Send mail
    uses: dawidd6/action-send-mail@v3
    with:
      # Required mail server address:
      server_address: smtp.gmail.com
      # Required mail server port:
      server_port: 465
      # Optional (recommended): mail server username:
      username: ${{secrets.MAIL_USERNAME}}
      # Optional (recommended) mail server password:
      password: ${{secrets.MAIL_PASSWORD}}
      # Required mail subject:
      subject: Github Actions job result
      # Required recipients' addresses:
      to: obiwan@example.com,yoda@example.com
      # Required sender full name (address can be skipped):
      from: Luke Skywalker # <user@example.com>
      # Optional whether this connection use TLS (default is true if server_port is 465)
      secure: true
      # Optional plain body:
      body: Build job of ${{github.repository}} completed successfully!
      # Optional HTML body read from file:
      html_body: file://README.html
      # Optional carbon copy recipients:
      cc: kyloren@example.com,leia@example.com
      # Optional blind carbon copy recipients:
      bcc: r2d2@example.com,hansolo@example.com
      # Optional recipient of the email response:
      reply_to: luke@example.com
      # Optional Message ID this message is replying to:
      in_reply_to: <random-luke@example.com>
      # Optional unsigned/invalid certificates allowance:
      ignore_cert: true
      # Optional converting Markdown to HTML (set content_type to text/html too):
      convert_markdown: true
      # Optional attachments:
      attachments: attachments.zip,git.diff,./dist/static/*.js
      # Optional priority: 'high', 'normal' (default) or 'low'
      priority: low